# Generated by Django 3.2.5 on 2021-07-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name_plural': 'Wishes'},
        ),
        migrations.AddField(
            model_name='wish',
            name='priority',
            field=models.CharField(choices=[('HI', 'High'), ('MD', 'Medium'), ('LO', 'Low')], default='HI', max_length=2),
        ),
    ]
