# Generated by Django 3.2.5 on 2021-07-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='priority',
            field=models.CharField(blank=True, choices=[('HI', 'High'), ('MD', 'Medium'), ('LO', 'Low')], default='HI', max_length=2),
        ),
    ]
