# Generated by Django 3.2.5 on 2021-07-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20210722_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
