# Generated by Django 3.2.5 on 2021-07-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20210710_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
