# Generated by Django 3.2.5 on 2021-07-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_customgroup_invited_users'),
        ('wishlist', '0003_alter_wish_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.customgroup'),
            preserve_default=False,
        ),
    ]
