# Generated by Django 3.2.5 on 2021-07-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_group',
            field=models.ManyToManyField(blank=True, related_name='custom_group', to='accounts.CustomGroup'),
        ),
    ]
