# Generated by Django 3.2.5 on 2021-07-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_custom_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_group',
        ),
    ]
