# Generated by Django 3.2.5 on 2021-07-15 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_custom_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customgroup',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='max_gift_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='priority',
            field=models.CharField(choices=[('DKK', 'DKK'), ('NOK', 'NOK'), ('¥', '¥'), ('$', '$')], default='NOK', max_length=3),
        ),
    ]
