# Generated by Django 3.2.5 on 2021-07-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210715_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgroup',
            old_name='priority',
            new_name='currency',
        ),
    ]
