# Generated by Django 3.2.5 on 2021-07-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210716_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='self_responsible',
            field=models.BooleanField(default=True),
        ),
    ]
