# Generated by Django 3.2.5 on 2021-07-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_self_responsible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='self_responsible',
            new_name='is_self_responsible',
        ),
    ]
