# Generated by Django 3.2.5 on 2021-07-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('accounts', '0013_rename_self_responsible_customuser_is_self_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='groups.CustomGroup', verbose_name='groups'),
        ),
    ]
