# Generated by Django 3.2.5 on 2021-07-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_notifications_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INV', 'Invitation'), ('ETC', 'Other')], default='ETC', max_length=3),
        ),
    ]
