# Generated by Django 3.2.5 on 2021-07-28 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_customgroup_closed'),
        ('accounts', '0019_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='groups.customgroup'),
        ),
    ]
