# Generated by Django 3.2.5 on 2021-07-19 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20210719_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
