# Generated by Django 3.2.5 on 2021-07-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_assignment_assignments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name_plural': 'Assignment'},
        ),
        migrations.AlterModelOptions(
            name='assignments',
            options={'verbose_name_plural': 'Assignments'},
        ),
        migrations.AddField(
            model_name='assignments',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
