# Generated by Django 3.2.5 on 2021-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20210727_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='assignment_rule',
            field=models.CharField(choices=[('M', 'Manual'), ('U', 'User-wise random'), ('R', 'Random')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='confirm_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
